%% figure 1 combined
%close all

figure('Position',[500 500 396 508])
subplot(2,1,1)
selectBats=[1];
[getAllBats,getAllBatsMimic,~,getAllBatsMimicP,~,getAllBatsMimicNP] = createGetAllBats(conditions, track,plotStore(selectBats,:),plotStoreCalls(selectBats,:));
atangerine = @(x)cellfun(@(y){atan(y)},x);
options = struct(...
    'namesBat',{{'all'}},...
    'conditions',{{'B-L','B-F', 'Catch'}},...
    'plotStore',{atangerine([getAllBats(1),getAllBats(2),getAllBats(3)])},...
    'Nstart',1,...
    'Nplot',200,...
    'plotColumn',0,...
    'track',{{track}},...
    'xlimits',[650,1300],... %[-70,50]
    'timebased',true,...
    'subplotting',false,...
    'occluder',false,...
    'titleFlag',false,...
    'unbend',false,...
    'colors',{{[1,155,99]/255,[116,22,247]/255,[116,255,247]/255,[116,22,247]/255}},...
    'lineThickness',1,...
    'labelTrack','target',...
    'showN',false, ...
    'halfwaypoint', 0);

miroTrackingPlot(options);
%xlim([580 1360])

selectCondition=[1,2,3];
plotCallRates(plotStoreCalls(selectBats,selectCondition),track,options.colors(selectCondition),options.xlimits, options.timebased,options.lineThickness,options.occluder,options.unbend,options.halfwaypoint);
